# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 12:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import precise_bbcode.fields
import project_manager.sub_plugins.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        ('users', '0001_initial'),
        ('plugins', '0001_initial'),
        ('requirements', '0001_initial'),
        ('tags', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('_configuration_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('configuration', precise_bbcode.fields.BBCodeTextField(blank=True, help_text='The configuration of the project. If too long, post on the forum and provide the link here. BBCode is allowed. 1024 char limit.', max_length=1024, no_rendered_field=True, null=True)),
                ('_description_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('description', precise_bbcode.fields.BBCodeTextField(blank=True, help_text='The full description of the project. BBCode is allowed. 1024 char limit.', max_length=1024, no_rendered_field=True, null=True)),
                ('_synopsis_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('synopsis', precise_bbcode.fields.BBCodeTextField(blank=True, help_text='A brief description of the project. BBCode is allowed. 128 char limit.', max_length=128, no_rendered_field=True, null=True)),
                ('topic', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(help_text="The name of the sub-plugin. Do not include the version, as that is added dynamically to the sub-plugin's page.", max_length=64)),
                ('basename', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator('^[a-z][0-9a-z_]*[0-9a-z]')])),
                ('slug', models.SlugField(blank=True, max_length=32)),
                ('logo', models.ImageField(blank=True, help_text="The sub-plugin's logo image.", null=True, upload_to=project_manager.sub_plugins.helpers.handle_sub_plugin_logo_upload)),
                ('contributors', models.ManyToManyField(related_name='subplugin_contributions', to='users.ForumUser')),
                ('download_requirements', models.ManyToManyField(related_name='subplugins', to='requirements.DownloadRequirement')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subplugins', to='users.ForumUser')),
                ('package_requirements', models.ManyToManyField(related_name='required_in_subplugins', to='packages.Package')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_plugins', to='plugins.Plugin')),
                ('pypi_requirements', models.ManyToManyField(related_name='required_in_subplugins', to='requirements.PyPiRequirement')),
                ('supported_games', models.ManyToManyField(related_name='subplugins', to='games.Game')),
                ('tags', models.ManyToManyField(related_name='subplugins', to='tags.Tag')),
                ('vcs_requirements', models.ManyToManyField(related_name='subplugins', to='requirements.VersionControlRequirement')),
            ],
            options={
                'verbose_name': 'SubPlugin',
                'verbose_name_plural': 'SubPlugins',
            },
        ),
        migrations.CreateModel(
            name='SubPluginImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=project_manager.sub_plugins.helpers.handle_sub_plugin_image_upload)),
                ('sub_plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sub_plugins.SubPlugin')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='SubPluginRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('version', models.CharField(help_text='The version for this release of the sub-plugin.', max_length=8, validators=[django.core.validators.RegexValidator('^[0-9][0-9a-z.]*[0-9a-z]')])),
                ('_notes_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('notes', precise_bbcode.fields.BBCodeTextField(blank=True, help_text='The notes for this particular release of the sub-plugin.', max_length=512, no_rendered_field=True, null=True)),
                ('zip_file', models.FileField(upload_to=project_manager.sub_plugins.helpers.handle_sub_plugin_zip_upload)),
                ('sub_plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='sub_plugins.SubPlugin')),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
            },
        ),
        migrations.AlterUniqueTogether(
            name='subplugin',
            unique_together=set([('plugin', 'basename'), ('plugin', 'slug'), ('plugin', 'name')]),
        ),
    ]
