# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('packages', '0002_auto_20171001_1805'),
        ('requirements', '0001_initial'),
        ('plugins', '0001_initial'),
        ('users', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugincontributor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ForumUser'),
        ),
        migrations.AddField(
            model_name='plugin',
            name='contributors',
            field=models.ManyToManyField(related_name='plugin_contributions', through='plugins.PluginContributor', to='users.ForumUser'),
        ),
        migrations.AddField(
            model_name='plugin',
            name='download_requirements',
            field=models.ManyToManyField(related_name='required_in_plugins', to='requirements.DownloadRequirement'),
        ),
        migrations.AddField(
            model_name='plugin',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to='users.ForumUser'),
        ),
        migrations.AddField(
            model_name='plugin',
            name='package_requirements',
            field=models.ManyToManyField(related_name='required_in_plugins', to='packages.Package'),
        ),
        migrations.AddField(
            model_name='plugin',
            name='pypi_requirements',
            field=models.ManyToManyField(related_name='required_in_plugins', to='requirements.PyPiRequirement'),
        ),
        migrations.AddField(
            model_name='plugin',
            name='supported_games',
            field=models.ManyToManyField(related_name='plugins', through='plugins.PluginGame', to='games.Game'),
        ),
        migrations.AddField(
            model_name='plugin',
            name='tags',
            field=models.ManyToManyField(related_name='plugins', through='plugins.PluginTag', to='tags.Tag'),
        ),
        migrations.AddField(
            model_name='plugin',
            name='vcs_requirements',
            field=models.ManyToManyField(related_name='required_in_plugins', to='requirements.VersionControlRequirement'),
        ),
        migrations.AlterUniqueTogether(
            name='subpluginpath',
            unique_together=set([('path', 'plugin')]),
        ),
        migrations.AlterUniqueTogether(
            name='plugintag',
            unique_together=set([('plugin', 'tag')]),
        ),
        migrations.AlterUniqueTogether(
            name='pluginrelease',
            unique_together=set([('plugin', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='plugingame',
            unique_together=set([('plugin', 'game')]),
        ),
        migrations.AlterUniqueTogether(
            name='plugincontributor',
            unique_together=set([('plugin', 'user')]),
        ),
    ]
