# Generated by Django 3.0.8 on 2020-07-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Download Requirement',
                'verbose_name_plural': 'Download Requirements',
            },
        ),
        migrations.CreateModel(
            name='PyPiRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'PyPi Requirement',
                'verbose_name_plural': 'PyPi Requirements',
            },
        ),
        migrations.CreateModel(
            name='VersionControlRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Version Control Requirement',
                'verbose_name_plural': 'Version Control Requirements',
            },
        ),
    ]
