# Generated by Django 3.2.8 on 2021-10-22 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[a-z]*')])),
                ('black_listed', models.BooleanField(default=False)),
            ],
        ),
    ]
