# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumUser',
            fields=[
                ('username', models.CharField(max_length=30, unique=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Forum User',
                'verbose_name_plural': 'Forum Users',
            },
        ),
    ]
