# Generated by Django 3.2.8 on 2021-10-22 13:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields
import model_utils.fields
import precise_bbcode.fields
import project_manager.common.helpers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('requirements', '0001_initial'),
        ('tags', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('name', models.CharField(help_text="The name of the project. Do not include the version, as that is added dynamically to the project's page.", max_length=64)),
                ('_configuration_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('configuration', precise_bbcode.fields.BBCodeTextField(blank=True, help_text='The configuration of the project. If too long, post on the forum and provide the link here. BBCode is allowed. 1024 char limit.', max_length=1024, no_rendered_field=True, null=True)),
                ('_description_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('description', precise_bbcode.fields.BBCodeTextField(blank=True, help_text='The full description of the project. BBCode is allowed. 1024 char limit.', max_length=1024, no_rendered_field=True, null=True)),
                ('logo', models.ImageField(blank=True, help_text="The project's logo image.", null=True, upload_to=project_manager.common.helpers.handle_project_logo_upload)),
                ('video', embed_video.fields.EmbedVideoField(help_text="The project's video.", null=True)),
                ('_synopsis_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('synopsis', precise_bbcode.fields.BBCodeTextField(blank=True, help_text='A brief description of the project. BBCode is allowed. 128 char limit.', max_length=128, no_rendered_field=True, null=True)),
                ('topic', models.IntegerField(blank=True, null=True, unique=True)),
                ('created', models.DateTimeField(verbose_name='created')),
                ('updated', models.DateTimeField(verbose_name='updated')),
                ('basename', models.CharField(blank=True, max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[a-z][0-9a-z_]*[0-9a-z]')])),
                ('slug', models.SlugField(blank=True, max_length=32, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='The version for this release of the project.', max_length=8, validators=[django.core.validators.RegexValidator('^[0-9][0-9a-z.]*[0-9a-z]')])),
                ('_notes_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('notes', precise_bbcode.fields.BBCodeTextField(blank=True, help_text='The notes for this particular release of the project.', max_length=512, no_rendered_field=True, null=True)),
                ('zip_file', models.FileField(upload_to=project_manager.common.helpers.handle_release_zip_file_upload)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
            ],
            options={
                'unique_together': {('package', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='PackageReleaseVersionControlRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, help_text='The version of the VCS package for this release of the project.', max_length=8, null=True, validators=[django.core.validators.RegexValidator('^[0-9][0-9a-z.]*[0-9a-z]')])),
                ('optional', models.BooleanField(default=False)),
                ('package_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packagerelease')),
                ('vcs_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.versioncontrolrequirement')),
            ],
            options={
                'unique_together': {('package_release', 'vcs_requirement')},
            },
        ),
        migrations.CreateModel(
            name='PackageReleasePyPiRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, help_text='The version of the PyPi package for this release of the project.', max_length=8, null=True, validators=[django.core.validators.RegexValidator('^[0-9][0-9a-z.]*[0-9a-z]')])),
                ('optional', models.BooleanField(default=False)),
                ('package_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packagerelease')),
                ('pypi_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.pypirequirement')),
            ],
            options={
                'unique_together': {('package_release', 'pypi_requirement')},
            },
        ),
        migrations.CreateModel(
            name='PackageReleasePackageRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, help_text='The version of the custom package for this release of the project.', max_length=8, null=True, validators=[django.core.validators.RegexValidator('^[0-9][0-9a-z.]*[0-9a-z]')])),
                ('optional', models.BooleanField(default=False)),
                ('package_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packagerelease')),
                ('package_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
            ],
            options={
                'unique_together': {('package_release', 'package_requirement')},
            },
        ),
        migrations.CreateModel(
            name='PackageReleaseDownloadRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('optional', models.BooleanField(default=False)),
                ('download_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.downloadrequirement')),
                ('package_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packagerelease')),
            ],
            options={
                'unique_together': {('package_release', 'download_requirement')},
            },
        ),
        migrations.AddField(
            model_name='packagerelease',
            name='download_requirements',
            field=models.ManyToManyField(related_name='required_in_package_releases', through='packages.PackageReleaseDownloadRequirement', to='requirements.DownloadRequirement'),
        ),
        migrations.AddField(
            model_name='packagerelease',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='packages.package'),
        ),
        migrations.AddField(
            model_name='packagerelease',
            name='package_requirements',
            field=models.ManyToManyField(related_name='required_in_package_releases', through='packages.PackageReleasePackageRequirement', to='packages.Package'),
        ),
        migrations.AddField(
            model_name='packagerelease',
            name='pypi_requirements',
            field=models.ManyToManyField(related_name='required_in_package_releases', through='packages.PackageReleasePyPiRequirement', to='requirements.PyPiRequirement'),
        ),
        migrations.AddField(
            model_name='packagerelease',
            name='vcs_requirements',
            field=models.ManyToManyField(related_name='required_in_package_releases', through='packages.PackageReleaseVersionControlRequirement', to='requirements.VersionControlRequirement'),
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=project_manager.common.helpers.handle_project_image_upload)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='packages.package')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
            ],
            options={
                'unique_together': {('package', 'game')},
            },
        ),
        migrations.CreateModel(
            name='PackageContributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.forumuser')),
            ],
            options={
                'unique_together': {('package', 'user')},
            },
        ),
        migrations.AddField(
            model_name='package',
            name='contributors',
            field=models.ManyToManyField(related_name='package_contributions', through='packages.PackageContributor', to='users.ForumUser'),
        ),
        migrations.AddField(
            model_name='package',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='users.forumuser'),
        ),
        migrations.AddField(
            model_name='package',
            name='supported_games',
            field=models.ManyToManyField(related_name='packages', through='packages.PackageGame', to='games.Game'),
        ),
        migrations.AddField(
            model_name='package',
            name='tags',
            field=models.ManyToManyField(related_name='packages', through='packages.PackageTag', to='tags.Tag'),
        ),
    ]
