# Generated by Django 3.0.8 on 2020-07-16 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('games', '0001_initial'),
        ('requirements', '0001_initial'),
        ('packages', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Tag'),
        ),
        migrations.AddField(
            model_name='packagereleaseversioncontrolrequirement',
            name='package_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.PackageRelease'),
        ),
        migrations.AddField(
            model_name='packagereleaseversioncontrolrequirement',
            name='vcs_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.VersionControlRequirement'),
        ),
        migrations.AddField(
            model_name='packagereleasepypirequirement',
            name='package_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.PackageRelease'),
        ),
        migrations.AddField(
            model_name='packagereleasepypirequirement',
            name='pypi_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.PyPiRequirement'),
        ),
        migrations.AddField(
            model_name='packagereleasepackagerequirement',
            name='package_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.PackageRelease'),
        ),
        migrations.AddField(
            model_name='packagereleasepackagerequirement',
            name='package_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Package'),
        ),
        migrations.AddField(
            model_name='packagereleasedownloadrequirement',
            name='download_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.DownloadRequirement'),
        ),
        migrations.AddField(
            model_name='packagereleasedownloadrequirement',
            name='package_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.PackageRelease'),
        ),
        migrations.AddField(
            model_name='packagerelease',
            name='download_requirements',
            field=models.ManyToManyField(related_name='required_in_package_releases', through='packages.PackageReleaseDownloadRequirement', to='requirements.DownloadRequirement'),
        ),
        migrations.AddField(
            model_name='packagerelease',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='packages.Package'),
        ),
        migrations.AddField(
            model_name='packagerelease',
            name='package_requirements',
            field=models.ManyToManyField(related_name='required_in_package_releases', through='packages.PackageReleasePackageRequirement', to='packages.Package'),
        ),
        migrations.AddField(
            model_name='packagerelease',
            name='pypi_requirements',
            field=models.ManyToManyField(related_name='required_in_package_releases', through='packages.PackageReleasePyPiRequirement', to='requirements.PyPiRequirement'),
        ),
        migrations.AddField(
            model_name='packagerelease',
            name='vcs_requirements',
            field=models.ManyToManyField(related_name='required_in_package_releases', through='packages.PackageReleaseVersionControlRequirement', to='requirements.VersionControlRequirement'),
        ),
        migrations.AddField(
            model_name='packageimage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='packages.Package'),
        ),
        migrations.AddField(
            model_name='packagegame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
        migrations.AddField(
            model_name='packagegame',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Package'),
        ),
        migrations.AddField(
            model_name='packagecontributor',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Package'),
        ),
        migrations.AddField(
            model_name='packagecontributor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ForumUser'),
        ),
        migrations.AddField(
            model_name='package',
            name='contributors',
            field=models.ManyToManyField(related_name='package_contributions', through='packages.PackageContributor', to='users.ForumUser'),
        ),
        migrations.AddField(
            model_name='package',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='users.ForumUser'),
        ),
        migrations.AddField(
            model_name='package',
            name='supported_games',
            field=models.ManyToManyField(related_name='packages', through='packages.PackageGame', to='games.Game'),
        ),
        migrations.AddField(
            model_name='package',
            name='tags',
            field=models.ManyToManyField(related_name='packages', through='packages.PackageTag', to='tags.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='packagetag',
            unique_together={('package', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='packagereleaseversioncontrolrequirement',
            unique_together={('package_release', 'vcs_requirement')},
        ),
        migrations.AlterUniqueTogether(
            name='packagereleasepypirequirement',
            unique_together={('package_release', 'pypi_requirement')},
        ),
        migrations.AlterUniqueTogether(
            name='packagereleasepackagerequirement',
            unique_together={('package_release', 'package_requirement')},
        ),
        migrations.AlterUniqueTogether(
            name='packagereleasedownloadrequirement',
            unique_together={('package_release', 'download_requirement')},
        ),
        migrations.AlterUniqueTogether(
            name='packagegame',
            unique_together={('package', 'game')},
        ),
        migrations.AlterUniqueTogether(
            name='packagecontributor',
            unique_together={('package', 'user')},
        ),
    ]
