# Generated by Django 3.2.8 on 2021-10-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(max_length=16, unique=True)),
                ('basename', models.CharField(max_length=16, unique=True)),
                ('slug', models.CharField(blank=True, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
    ]
