# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 14:15
import django.core.validators
from django.db import migrations, models
import project_manager.packages.helpers
import project_manager.plugins.helpers
import project_manager.sub_plugins.helpers
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='configuration',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, help_text='The configuration of the project. If too long, post on the forum and provide the link here. BBCode is allowed. 1024 char limit.', max_length=1024, no_rendered_field=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, help_text='The full description of the project. BBCode is allowed. 1024 char limit.', max_length=1024, no_rendered_field=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='logo',
            field=models.ImageField(blank=True, help_text="The package's logo image.", null=True, upload_to=project_manager.packages.helpers.handle_package_logo_upload),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(help_text="The name of the package. Do not include the version, as that is added dynamically to the package's page.", max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='synopsis',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, help_text='A brief description of the project. BBCode is allowed. 128 char limit.', max_length=128, no_rendered_field=True, null=True),
        ),
        migrations.AlterField(
            model_name='packagerelease',
            name='notes',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, help_text='The notes for this particular release of the package.', max_length=512, no_rendered_field=True, null=True),
        ),
        migrations.AlterField(
            model_name='packagerelease',
            name='version',
            field=models.CharField(help_text='The version for this release of the package.', max_length=8, validators=[django.core.validators.RegexValidator(b'^[0-9][0-9a-z.]*[0-9a-z]')]),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='configuration',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, help_text='The configuration of the project. If too long, post on the forum and provide the link here. BBCode is allowed. 1024 char limit.', max_length=1024, no_rendered_field=True, null=True),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='description',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, help_text='The full description of the project. BBCode is allowed. 1024 char limit.', max_length=1024, no_rendered_field=True, null=True),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='logo',
            field=models.ImageField(blank=True, help_text="The plugin's logo image.", null=True, upload_to=project_manager.plugins.helpers.handle_plugin_logo_upload),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(help_text="The name of the plugin. Do not include the version, as that is added dynamically to the plugin's page.", max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='synopsis',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, help_text='A brief description of the project. BBCode is allowed. 128 char limit.', max_length=128, no_rendered_field=True, null=True),
        ),
        migrations.AlterField(
            model_name='pluginrelease',
            name='notes',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, help_text='The notes for this particular release of the plugin.', max_length=512, no_rendered_field=True, null=True),
        ),
        migrations.AlterField(
            model_name='pluginrelease',
            name='version',
            field=models.CharField(help_text='The version for this release of the plugin.', max_length=8, validators=[django.core.validators.RegexValidator(b'^[0-9][0-9a-z.]*[0-9a-z]')]),
        ),
        migrations.AlterField(
            model_name='subplugin',
            name='configuration',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, help_text='The configuration of the project. If too long, post on the forum and provide the link here. BBCode is allowed. 1024 char limit.', max_length=1024, no_rendered_field=True, null=True),
        ),
        migrations.AlterField(
            model_name='subplugin',
            name='description',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, help_text='The full description of the project. BBCode is allowed. 1024 char limit.', max_length=1024, no_rendered_field=True, null=True),
        ),
        migrations.AlterField(
            model_name='subplugin',
            name='logo',
            field=models.ImageField(blank=True, help_text="The sub-plugin's logo image.", null=True, upload_to=project_manager.sub_plugins.helpers.handle_sub_plugin_logo_upload),
        ),
        migrations.AlterField(
            model_name='subplugin',
            name='name',
            field=models.CharField(help_text="The name of the sub-plugin. Do not include the version, as that is added dynamically to the sub-plugin's page.", max_length=64),
        ),
        migrations.AlterField(
            model_name='subplugin',
            name='synopsis',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, help_text='A brief description of the project. BBCode is allowed. 128 char limit.', max_length=128, no_rendered_field=True, null=True),
        ),
        migrations.AlterField(
            model_name='subpluginrelease',
            name='notes',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, help_text='The notes for this particular release of the sub-plugin.', max_length=512, no_rendered_field=True, null=True),
        ),
        migrations.AlterField(
            model_name='subpluginrelease',
            name='version',
            field=models.CharField(help_text='The version for this release of the sub-plugin.', max_length=8, validators=[django.core.validators.RegexValidator(b'^[0-9][0-9a-z.]*[0-9a-z]')]),
        ),
    ]
