# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-13 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_added_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='topic',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='topic',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subplugin',
            name='topic',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
