# Generated by Django 3.2.8 on 2021-11-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.AlterModelOptions(
            name='plugin',
            options={'verbose_name': 'Plugin', 'verbose_name_plural': 'Plugins'},
        ),
        migrations.AlterUniqueTogether(
            name='packagerelease',
            unique_together={('package', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='subpluginrelease',
            unique_together={('sub_plugin', 'version')},
        ),
    ]
