# Generated by Django 3.2.9 on 2021-11-13 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('project_manager', '0004_auto_20211103_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagerelease',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_releases', to='users.forumuser'),
        ),
        migrations.AddField(
            model_name='pluginrelease',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_releases', to='users.forumuser'),
        ),
        migrations.AddField(
            model_name='subpluginrelease',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_plugin_releases', to='users.forumuser'),
        ),
    ]
