# Generated by Django 4.0.2 on 2022-02-05 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('project_manager', '0005_release_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.forumuser'),
        ),
        migrations.AlterField(
            model_name='packagerelease',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='users.forumuser'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.forumuser'),
        ),
        migrations.AlterField(
            model_name='pluginrelease',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='users.forumuser'),
        ),
        migrations.AlterField(
            model_name='subplugin',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.forumuser'),
        ),
        migrations.AlterField(
            model_name='subpluginrelease',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='users.forumuser'),
        ),
    ]
