# Generated by Django 4.0.3 on 2022-03-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(max_length=16, unique=True)),
                ('basename', models.CharField(max_length=16, unique=True)),
                ('slug', models.CharField(blank=True, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('icon', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
